name: Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Linter & Formatter
        run: |
          pip install flake8 black
      - name: Run flake8
        run: flake8 . --max-line-length=100
      - name: Run black (check only)
        run: black --check .
